# Generated by Django 5.1.7 on 2025-03-11 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='EnumColor',
            fields=[
                ('value', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('user_friendly_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EnumSector',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='EnumType',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='EvenementRoom',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='GroupTD',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ClassLinkDepart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.department')),
            ],
        ),
        migrations.CreateModel(
            name='Association',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('user_email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('unique_color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.enumcolor')),
                ('sector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.enumsector')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.enumtype')),
            ],
        ),
        migrations.CreateModel(
            name='EvenementLinkEventRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.evenementroom')),
            ],
        ),
        migrations.CreateModel(
            name='ClassLinkTD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('td', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.grouptd')),
            ],
        ),
        migrations.CreateModel(
            name='InsaClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_hour', models.TimeField()),
                ('end_hour', models.TimeField()),
                ('desc', models.CharField(blank=True, max_length=255, null=True)),
                ('link_depart', models.ManyToManyField(through='backend.ClassLinkDepart', to='backend.department')),
                ('link_td', models.ManyToManyField(through='backend.ClassLinkTD', to='backend.grouptd')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClassLinkTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insa_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.insaclass')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='classlinktd',
            name='insa_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.insaclass'),
        ),
        migrations.CreateModel(
            name='ClassLinkRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insa_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.insaclass')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.room')),
            ],
        ),
        migrations.AddField(
            model_name='classlinkdepart',
            name='insa_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.insaclass'),
        ),
        migrations.CreateModel(
            name='InsaEvenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_hour', models.TimeField()),
                ('end_hour', models.TimeField()),
                ('desc', models.CharField(blank=True, max_length=255, null=True)),
                ('associated_link', models.CharField(max_length=510)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.association')),
                ('evenement_link_event_room', models.ManyToManyField(through='backend.EvenementLinkEventRoom', to='backend.evenementroom')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='evenementlinkeventroom',
            name='evenement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenement_link_evenement_room', to='backend.insaevenement'),
        ),
        migrations.AddField(
            model_name='insaclass',
            name='link_room',
            field=models.ManyToManyField(through='backend.ClassLinkRoom', to='backend.room'),
        ),
        migrations.AddField(
            model_name='insaclass',
            name='link_teacher',
            field=models.ManyToManyField(through='backend.ClassLinkTeacher', to='backend.teacher'),
        ),
        migrations.CreateModel(
            name='UserLinkTD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_td', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.grouptd')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_td', models.ManyToManyField(related_name='users', through='backend.UserLinkTD', to='backend.grouptd')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='userlinktd',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.userprofile'),
        ),
    ]
