# Generated by Django 5.1.7 on 2025-03-13 11:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insaclass',
            name='id',
        ),
        migrations.RemoveField(
            model_name='insaevenement',
            name='id',
        ),
        migrations.AddField(
            model_name='insaclass',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='insaevenement',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
