# Generated by Django 5.1.7 on 2025-03-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_insaclass_id_remove_insaevenement_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insaclass',
            name='uid',
            field=models.CharField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='insaevenement',
            name='uid',
            field=models.CharField(editable=False, primary_key=True, serialize=False),
        ),
    ]
