# Generated by Django 5.2 on 2025-04-03 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouptd',
            name='departement',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
