# Generated by Django 5.2 on 2025-04-14 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_grouptd_departement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouptd',
            name='departement',
        ),
    ]
