services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: db.postgresql
      POSTGRES_USER: root
      POSTGRES_PASSWORD: toto123
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    image: insaccess-backend:latest
    environment:
      - DB_HOST=db
      - DB_NAME=db.postgresql
      - DB_USER=root
      - DB_PASSWORD=toto123
      - DJANGO_SETTINGS_MODULE=config.settings
      - PYTHONPATH=/app
      - DOCKER_ENV=true
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    image: insaccess-frontend:latest
    environment:
      - REACT_APP_API_URL="http://192.168.1.25:8000"
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  db_data:
