services:
  db:
    image: docker.io/library/postgres:latest
    environment:
      POSTGRES_DB: db.postgresql
      POSTGRES_USER: root
      POSTGRES_PASSWORD: toto123
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    working_dir: /core
    volumes:
      - .:/core
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=db.postgresql
      - DB_USER=root
      - DB_PASSWORD=toto123
      - DJANGO_SETTINGS_MODULE=config.settings
      - PYTHONPATH=/core
volumes:
  postgres_data: