# Generated by Django 5.2 on 2025-05-05 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('color', models.CharField(default='default', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='EnumColorTheme',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='EnumSector',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='EnumType',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='GroupTD',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='AssociationPublisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.association')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClassLinkDepart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.department')),
            ],
        ),
        migrations.AddField(
            model_name='association',
            name='sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.enumsector'),
        ),
        migrations.AddField(
            model_name='association',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.enumtype'),
        ),
        migrations.CreateModel(
            name='ClassLinkTD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('td', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.grouptd')),
            ],
        ),
        migrations.CreateModel(
            name='InsaClass',
            fields=[
                ('uid', models.CharField(editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time_stamp', models.DateTimeField()),
                ('start_hour', models.DateTimeField()),
                ('end_hour', models.DateTimeField()),
                ('time_created', models.DateTimeField()),
                ('time_last_modified', models.DateTimeField()),
                ('sequence', models.IntegerField(null=True)),
                ('link_depart', models.ManyToManyField(through='core.ClassLinkDepart', to='core.department')),
                ('link_td', models.ManyToManyField(through='core.ClassLinkTD', to='core.grouptd')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClassLinkTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insa_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.insaclass')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='classlinktd',
            name='insa_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.insaclass'),
        ),
        migrations.CreateModel(
            name='ClassLinkRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insa_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.insaclass')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.room')),
            ],
        ),
        migrations.AddField(
            model_name='classlinkdepart',
            name='insa_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.insaclass'),
        ),
        migrations.AddField(
            model_name='insaclass',
            name='link_room',
            field=models.ManyToManyField(through='core.ClassLinkRoom', to='core.room'),
        ),
        migrations.AddField(
            model_name='insaclass',
            name='link_teacher',
            field=models.ManyToManyField(through='core.ClassLinkTeacher', to='core.teacher'),
        ),
        migrations.CreateModel(
            name='InsaEvenement',
            fields=[
                ('uid', models.CharField(editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time_stamp', models.DateTimeField()),
                ('start_hour', models.DateTimeField()),
                ('end_hour', models.DateTimeField()),
                ('time_created', models.DateTimeField()),
                ('time_last_modified', models.DateTimeField()),
                ('sequence', models.IntegerField(null=True)),
                ('associated_link', models.CharField(max_length=510)),
                ('location', models.CharField(max_length=510)),
                ('info', models.CharField()),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.association')),
                ('desc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.title')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='insaclass',
            name='desc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.title'),
        ),
        migrations.CreateModel(
            name='UserColoredClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(verbose_name=7)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.title')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserLinkTD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_td', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.grouptd')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_theme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.enumcolortheme')),
                ('link_td', models.ManyToManyField(related_name='users', through='core.UserLinkTD', to='core.grouptd')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='userlinktd',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userprofile'),
        ),
    ]
