# Generated by Django 5.2 on 2025-04-24 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnumColorTheme',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='color_theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.enumcolortheme'),
        ),
    ]
