# Generated by Django 4.0 on 2025-06-23 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_association_color_usercoloredevent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insaclass',
            name='link_depart',
            field=models.ManyToManyField(through='core.ClassLinkDepart', to='core.Department'),
        ),
        migrations.AlterField(
            model_name='insaclass',
            name='link_room',
            field=models.ManyToManyField(through='core.ClassLinkRoom', to='core.Room'),
        ),
        migrations.AlterField(
            model_name='insaclass',
            name='link_td',
            field=models.ManyToManyField(through='core.ClassLinkTD', to='core.GroupTD'),
        ),
        migrations.AlterField(
            model_name='insaclass',
            name='link_teacher',
            field=models.ManyToManyField(through='core.ClassLinkTeacher', to='core.Teacher'),
        ),
        migrations.AlterField(
            model_name='insaclass',
            name='uid',
            field=models.CharField(editable=False, max_length=256, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='insaevenement',
            name='info',
            field=models.CharField(max_length=510),
        ),
        migrations.AlterField(
            model_name='insaevenement',
            name='uid',
            field=models.CharField(editable=False, max_length=256, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='link_td',
            field=models.ManyToManyField(related_name='users', through='core.UserLinkTD', to='core.GroupTD'),
        ),
    ]
