# Generated by Django 5.2 on 2025-04-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_enumcolortheme_userprofile_color_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insaclass',
            name='sequence',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='insaevenement',
            name='sequence',
            field=models.IntegerField(null=True),
        ),
    ]
