# Generated by Django 4.2.7 on 2025-08-31 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_insaclass_link_depart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ics_uid',
            field=models.CharField(default='', editable=False, max_length=64, unique=True),
        ),
    ]
