# Generated by Django 5.2 on 2025-04-30 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_insaclass_sequence_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='associationpublisher',
            old_name='assocation',
            new_name='association',
        ),
    ]
