# Generated by Django 4.2.7 on 2025-09-05 06:54

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userprofile_ics_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnumLanguage',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='color_theme',
            field=models.ForeignKey(default=core.models.EnumColorTheme.get_default_theme, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.enumcolortheme'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='language',
            field=models.ForeignKey(default=core.models.EnumLanguage.get_default_language, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.enumlanguage'),
        ),
    ]
