# Generated by Django 5.2 on 2025-05-05 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_assocation_associationpublisher_association'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='association',
            name='unique_color',
        ),
        migrations.RemoveField(
            model_name='evenementlinkeventroom',
            name='evenement',
        ),
        migrations.RemoveField(
            model_name='evenementlinkeventroom',
            name='room',
        ),
        migrations.RemoveField(
            model_name='insaevenement',
            name='evenement_link_event_room',
        ),
        migrations.AddField(
            model_name='association',
            name='color',
            field=models.CharField(default='default', max_length=7),
        ),
        migrations.AddField(
            model_name='insaevenement',
            name='location',
            field=models.CharField(default='temp', max_length=510),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='EnumColor',
        ),
        migrations.DeleteModel(
            name='EvenementLinkEventRoom',
        ),
        migrations.DeleteModel(
            name='EvenementRoom',
        ),
    ]
