# Generated by Django 5.2 on 2025-05-05 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_association_unique_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insaevenement',
            name='info',
            field=models.CharField(default='temp'),
            preserve_default=False,
        ),
    ]
