# Generated by Django 4.2.7 on 2025-09-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_userrelationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrelationship',
            name='type',
            field=models.CharField(choices=[('PE', 'pending'), ('FR', 'friend')], max_length=2),
        ),
    ]
