# Generated by Django 4.2.7 on 2025-09-15 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_userrelationship_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLinkAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_assos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.association')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='link_assos',
            field=models.ManyToManyField(related_name='users', through='core.UserLinkAssociation', to='core.association'),
        ),
    ]
