# Generated by Django 4.2.7 on 2025-09-16 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_userlinkassociation_userprofile_link_assos'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cas_auto_sync',
            field=models.BooleanField(default=False),
        ),
    ]
