# Generated by Django 4.2.7 on 2025-09-18 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_userprofile_cas_auto_sync'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='departement_name',
            field=models.CharField(default='STPI', max_length=8),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='departement_year',
            field=models.CharField(default='1', max_length=1),
        ),
    ]
