# Generated by Django 4.2.7 on 2025-09-19 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_userprofile_departement_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='departement_name',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='departement_year',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
