# Generated by Django 4.2.7 on 2025-11-18 20:03

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_cleanup_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='association',
            name='sector_id',
        ),
        migrations.RemoveField(
            model_name='association',
            name='type_id',
        ),
        migrations.RemoveField(
            model_name='associationpublisher',
            name='association_id',
        ),
        migrations.RemoveField(
            model_name='classlinkdepart',
            name='depart_id',
        ),
        migrations.RemoveField(
            model_name='classlinkroom',
            name='room_id',
        ),
        migrations.RemoveField(
            model_name='classlinktd',
            name='td_id',
        ),
        migrations.RemoveField(
            model_name='classlinkteacher',
            name='teacher_id',
        ),
        migrations.RemoveField(
            model_name='insaclass',
            name='desc_id',
        ),
        migrations.RemoveField(
            model_name='insaevenement',
            name='association_id',
        ),
        migrations.RemoveField(
            model_name='insaevenement',
            name='desc_id',
        ),
        migrations.RemoveField(
            model_name='usercoloredevent',
            name='title_id',
        ),
        migrations.RemoveField(
            model_name='userlinkassociation',
            name='name_assos_id',
        ),
        migrations.RemoveField(
            model_name='userlinktd',
            name='name_td_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='color_theme_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='language_id',
        ),
        migrations.AlterField(
            model_name='association',
            name='sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.enumsector'),
        ),
        migrations.AlterField(
            model_name='association',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.enumtype'),
        ),
        migrations.AlterField(
            model_name='associationpublisher',
            name='association',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.association'),
        ),
        migrations.AlterField(
            model_name='classlinkdepart',
            name='depart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.department'),
        ),
        migrations.AlterField(
            model_name='classlinkroom',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.room'),
        ),
        migrations.AlterField(
            model_name='classlinktd',
            name='td',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.grouptd'),
        ),
        migrations.AlterField(
            model_name='classlinkteacher',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.teacher'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='enumcolortheme',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='grouptd',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='insaclass',
            name='desc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.title'),
        ),
        migrations.AlterField(
            model_name='insaevenement',
            name='association',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.association'),
        ),
        migrations.AlterField(
            model_name='insaevenement',
            name='desc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.title'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='usercoloredevent',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.title'),
        ),
        migrations.AlterField(
            model_name='userlinkassociation',
            name='name_assos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.association'),
        ),
        migrations.AlterField(
            model_name='userlinktd',
            name='name_td',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.grouptd'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='color_theme',
            field=models.ForeignKey(default=core.models.EnumColorTheme.get_default_theme, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.enumcolortheme'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='language',
            field=models.ForeignKey(default=core.models.EnumLanguage.get_default_language, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.enumlanguage'),
        ),
    ]
